"""Add saved column to Ticket

Revision ID: 205061528756
Revises: b03f6392dff8
Create Date: 2024-12-24 10:29:30.407587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '205061528756'
down_revision = 'b03f6392dff8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('saved', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('saved')

    # ### end Alembic commands ###
